import os
import random
import re
import sys

DAMPING = 0.85
SAMPLES = 10000


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python pagerank.py corpus")
    corpus = crawl(sys.argv[1])
    ranks = sample_pagerank(corpus, DAMPING, SAMPLES)
    print(f"PageRank Results from Sampling (n = {SAMPLES})")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")
    ranks = iterate_pagerank(corpus, DAMPING)
    print(f"PageRank Results from Iteration")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")


def crawl(directory):
    """
    Parse a directory of HTML pages and check for links to other pages.
    Return a dictionary where each key is a page, and values are
    a list of all other pages in the corpus that are linked to by the page.
    """
    pages = dict()

    # Extract all links from HTML files
    for filename in os.listdir(directory):
        if not filename.endswith(".html"):
            continue
        with open(os.path.join(directory, filename)) as f:
            contents = f.read()
            links = re.findall(r"<a\s+(?:[^>]*?)href=\"([^\"]*)\"", contents)
            pages[filename] = set(links) - {filename}

    # Only include links to other pages in the corpus
    for filename in pages:
        pages[filename] = set(
            link for link in pages[filename] if link in pages
        )

    return pages


def transition_model(corpus, page, damping_factor):
    """
    Return a probability distribution over which page to visit next,
    given a current page.

    With probability `damping_factor`, choose a link at random
    linked to by `page`. With probability `1 - damping_factor`, choose
    a link at random chosen from all pages in the corpus.
    """
    # raise NotImplementedError

    # Use multiply 10_000 to avoid float problems
    # Get probabilities for damping_factor and for 1 - damping_factor
    probability_corpus = int((1 - damping_factor) * 10_000 / len(corpus))
    links_probability = 0
    if corpus[page]:
        links_probability = int(damping_factor * 10_000 / len(corpus[page]))

    # Get probability distribution
    distribution = {}

    for link in corpus:
        distribution[link] = (
            distribution.get(link, 0) * 10_000 + probability_corpus
        ) / 10_000
        if link == page:
            for l in corpus[page]:
                distribution[l] = (
                    distribution.get(l, 0) * 10_000 + links_probability
                ) / 10_000

    return distribution


def sample_pagerank(corpus, damping_factor, n):
    """
    Return PageRank values for each page by sampling `n` pages
    according to transition model, starting with a page at random.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # raise NotImplementedError

    # Initialize a visits dictionary
    visits = {link: 0 for link in corpus}

    # The first sample should be generated by choosing from a page at random.
    page = random.choice(list(corpus))
    visits[page] += 1

    # For each of the remaining samples, the next sample should be generated from the previous sample based on the previous sample’s transition model.
    for _ in range(n - 1):
        # Get the dictionary of probabilities with the transition model
        probabilities = transition_model(corpus, page, damping_factor)

        # Pick a next page
        page = random.choices(
            list(probabilities.keys()), list(probabilities.values())
        )[0]

        # Change the number of page visits
        visits[page] += 1

    # Normalize visits
    pagerank = {page: num / n for page, num in visits.items()}

    return pagerank


def iterate_pagerank(corpus, damping_factor):
    """
    Return PageRank values for each page by iteratively updating
    PageRank values until convergence.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # raise NotImplementedError


if __name__ == "__main__":
    main()
