import os
import random
import re
import sys

DAMPING = 0.85
SAMPLES = 10000


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python pagerank.py corpus")
    corpus = crawl(sys.argv[1])
    ranks = sample_pagerank(corpus, DAMPING, SAMPLES)
    print(f"PageRank Results from Sampling (n = {SAMPLES})")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")
    ranks = iterate_pagerank(corpus, DAMPING)
    print(f"PageRank Results from Iteration")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")


def crawl(directory):
    """
    Parse a directory of HTML pages and check for links to other pages.
    Return a dictionary where each key is a page, and values are
    a list of all other pages in the corpus that are linked to by the page.
    """
    pages = dict()

    # Extract all links from HTML files
    for filename in os.listdir(directory):
        if not filename.endswith(".html"):
            continue
        with open(os.path.join(directory, filename)) as f:
            contents = f.read()
            links = re.findall(r"<a\s+(?:[^>]*?)href=\"([^\"]*)\"", contents)
            pages[filename] = set(links) - {filename}

    # Only include links to other pages in the corpus
    for filename in pages:
        pages[filename] = set(
            link for link in pages[filename] if link in pages
        )

    return pages


def transition_model(corpus, page, damping_factor):
    """
    Return a probability distribution over which page to visit next,
    given a current page.

    With probability `damping_factor`, choose a link at random
    linked to by `page`. With probability `1 - damping_factor`, choose
    a link at random chosen from all pages in the corpus.
    """
    # raise NotImplementedError

    # Initialize a distribution of probabilities dictionary with an equal probability
    eq_prob = (1 - damping_factor) / len(corpus)
    distribution = {page: eq_prob for page in corpus.keys()}

    # Get probabilities for links of the page if the page has them
    if corpus[page]:
        links = corpus[page]
        link_prob = damping_factor / len(links)
        for link in links:
            distribution[link] += link_prob

    return distribution


def sample_pagerank(corpus, damping_factor, n):
    """
    Return PageRank values for each page by sampling `n` pages
    according to transition model, starting with a page at random.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # raise NotImplementedError

    # Initialize a visits dictionary
    visits = {link: 0 for link in corpus}

    # The first sample should be generated by choosing from a page at random.
    page = random.choice(list(corpus))
    visits[page] += 1

    # For each of the remaining samples, the next sample should be generated from the previous sample based on the previous sample’s transition model.
    for _ in range(n - 1):
        # Get the dictionary of probabilities with the transition model
        probabilities = transition_model(corpus, page, damping_factor)

        # Pick a next page
        page = random.choices(
            list(probabilities.keys()), list(probabilities.values())
        )[0]

        # Change the number of page visits
        visits[page] += 1

    # Normalize visits
    pagerank = {page: num / n for page, num in visits.items()}

    return pagerank


def iterate_pagerank(corpus, damping_factor):
    """
    Return PageRank values for each page by iteratively updating
    PageRank values until convergence.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    # raise NotImplementedError

    # Specified accuracy
    ACCURACY = 0.001

    N = len(corpus)
    random_rank = (1 - damping_factor) / N

    # Initialize the initial page rank dictionaries
    init_rank = 1 / N
    page_ranks = {page: init_rank for page in corpus}

    # Loop until the accuracy not enough
    while True:
        # Create iter_ranks dictionary for page ranks in the current iteration
        iter_ranks = {page: random_rank for page in corpus}

        # Change values of iter_ranks
        for page in corpus:
            if corpus[page]:
                share = damping_factor * page_ranks[page] / len(corpus[page])
                for link in corpus[page]:
                    iter_ranks[link] += share
            else:
                share = damping_factor * page_ranks[page] / N
                for link in corpus:
                    iter_ranks[link] += share

        # Calculate divergence between page_ranks and iter_ranks
        diff = max(
            abs(iter_ranks[page] - page_ranks[page]) for page in page_ranks
        )

        # Update page_ranks into iter_ranks
        page_ranks = iter_ranks

        # Check accuracy
        if diff < ACCURACY:
            break

    return page_ranks


if __name__ == "__main__":
    main()
